### ISSUE TITLE
[ Feature Request ] Direct generate to VST3 plugin

### ISSUE THREAD

**Issue by agdsat134** [SoundStacks/cmajor#10]
From what I understand, at the moment you need to first render to a JUCE patch, then compile the JUCE patch in order to use it as a plugin. Would it be possible to directly compile it to a VST3 plugin?

**Comment by julianstorer** [comment]
I'm just revisiting some old issues and FRs.. We're doing a lot of active work in this area and will have a totally new plugin system out before too long, so I'm going to close this FR :)
