### ISSUE TITLE
Possible to console.log in UI files?

### ISSUE THREAD

**Issue by wildyeast** [SoundStacks/cmajor#25]
I'm experimenting with custom UIs for Cmajor patches and I have a hard time debugging the JS files. In the [docs](https://cmajor.dev/docs/PatchFormat#built-in-javascript-utility-classes) you casually mention the possibility to print logs to the console, but I can't see them anywhere. Any ideas?

**Comment by julianstorer** [comment]
That's not a Cmajor thing, it's just standard javascript: you do a `console.log (whatever)` to print to the console.

**Comment by julianstorer** [comment]
You'd open the browser debug panel (right-click usually has it on the popup menu, and there are key shortcuts for this), and it's all in there.

I hadn't thought of having something that redirects logging back to the console app's output, that's not a bad idea for a feature. But normally whenever you're developing a javascript UI, people tend to have the browser debug panel going

**Comment by wildyeast** [comment]
I had not realised that the patch window is, in fact, a browser. Thanks!
